### ISSUE TITLE
Is is correct to use `running_var`?

### ISSUE THREAD

**Issue by calofmijuck** [MrGoriay/pwlu-pytorch#2]
I'm new to deep learning, so please correct me if I'm wrong.

During the statistics collection, the paper uses _running standard deviation of input_ $x$. But it seems to me that your code uses `running_var` instead. Was this intentional? Or would it be correct to use `x.std()` instead of `x.var()`?

Thanks.

**Comment by MrGoriay** [comment]
No, you are right, it was not intentional, it just worked fine, so i didn't notice. Changed the code, closing.
